### ISSUE TITLE
The incoming request has too many parameters. The server supports a maximum of 2100 parameters.

### ISSUE THREAD

**Issue by brianzinken** [realm/realm-connectors#10]
**Describe the bug**
Using v2.5.0 of the MSSQl adapter will crash with the error message "The incoming request has too many parameters. The server supports a maximum of 2100 parameters."  
**Expected behavior**
Adapter will process requests without crashing.
**How to Reproduce**
Adapter ran for nearly 2 days, but then crashed.
**Context:**
 - Product: 
    [x] MS-SQL Adapter
    [ ] PostgreSQL Adapter
 - Version: v2.5.0 - Adapter - Realm Cloud v3.20.1
 - OS:

**Comment by brianzinken** [comment]
I downloaded realm-mssql-adapters-2.5.0.tgz from the address where I have been downloading previous versions. Please let me know if I can provide any information to help.  This project does have a wide legacy table with 180 columns that could be related to issue in the v2.5.0 release notes.

**Comment by kneth** [comment]
@brianzinken If possible, I would like to see the actual error message (or log) and the SQL schema. You can either create a support ticket or send me a direct email (`kg--at--realm--io`).

**Comment by bmunkholm** [comment]
@brianzinken Creating a [support ticket](https://support.realm.io) would be appreciated as this repo isn't being monitored for support. (Issues will be disabled shortly).
