### ISSUE TITLE
MSSQL data connector - Azure SQL Database 

### ISSUE THREAD

**Issue by sonuneer** [realm/realm-connectors#8]
**Describe the bug**
I’m working on MSSQL data connector, where Azure MSSQL DB(dbsqlsyncdemo.database.windows.net) and Realm on cloud - realms://nsnewinstance.us1a.cloud.realm.io is throwing error.

Error detail-
(node:15672) UnhandledPromiseRejectionWarning: Error: Unable to open a realm at Path 'C:\MSSQL_Realm\mssql-test\.\state\LoaderState.realm.management':make_dir() failed: No such file or directory Path:.
at New LocalState(C:\Users\kneth\Projects\data-adapters\packages\mssql\src\SQLServerRealmLoader.ts:32:28)
at main(C:\MSSQL_Realm\mssql-test\loader.js:68:7)
(node:15672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not ....

**Expected behavior**
Followed the following link - https://docs.realm.io/sync/backend-integration/mssql-data-connector#releases 

**How to Reproduce**
Followed the following link - https://docs.realm.io/sync/backend-integration/mssql-data-connector#releases 

**Context:**
 - Product: 
    [YES ] MS-SQL Adapter  

 - Version: realm-mssql-adapters-2.4.1.tgz
 - OS: WINDOWS 10

**Comment by bmunkholm** [comment]
@sonuneer Could I please ask you to open a ticket our [support portal](https://support.realm.io) as this repo is not monitored for support issues (Issues will be disabled shortly to avoid this misunderstanding)?
