### ISSUE TITLE
PostgreSQL Adapter - Realm class name to PostgreSQL schema name mapping

### ISSUE THREAD

**Issue by qexpres** [realm/realm-connectors#9]
**Product**
[ ] MS-SQL Adapter
[X] PostgreSQL Adapter

**Is your feature request related to a problem? Please describe.**
Our company uses multiple PostgreSQL schemas (not to be confused with Realm Object Schemas) and currently you are only allowed to set a global schema to use instead of "public". I would like to define the schema to use for specific class names.

**Describe the solution you'd like**
In the adapter configuration I would like to be able to specify which schema name to use for a given class name. Basically, if I could use the `mapRealmClassName` callback to either specify a qualified name as a string (e.g. `schema.table`) or as an object (e.g. `{ table: 'table', schema: 'schema' }`) which is pretty similar to how to defined Object Schema properties nowadays.

**Describe alternatives you've considered**
I tried using the `mapRealmClassName` callback. Right now you can only specify the table, unfortunately. `schema.table` results in `"public"."schema.table"` and `"schema"."table"` results in a Postgres error as the query tries to create a table called `"public".""schema"."table""`...
Another thing I considered to do it to dynamically change the adapter's dbSchema property, but I'm afraid that will create conflicts with other asynchronous jobs.
Lastly, I wonder if I can extend the library somehow to implement this feature for personal use...

**Additional context**
Running `realm-postgres-adapters-1.9.0` on MacOS, RDS PostgreSQL 9.6, Realm Cloud...

**Comment by bmunkholm** [comment]
@qexpres Sorry about the lacking response as this repo is not being monitored for support issues. We will disable issues to avoid misunderstandings.  Could I ask you to create a ticket in our [support portal](https://support.realm.io) instead?  
Sorry about the hassle. Thanks!
